name: DevOps Build Check

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Проверяем код репозитория
      uses: actions/checkout@v4

    - name: Собираем тестовый Docker-образ
      run: |
        docker build -t test-image .
        echo "Сборка образа прошла успешно!"
